first_name: "Rohith"
last_name: "Yadav"
pronouns : "he/him"
gender : "Male"
email: "rohith123@example.com"
phone: "+1-123-456-7890"
address: "123 Main St"
city: "New York"
state: "New York"
zip: "10001"
country: "United States"
referral_source: "LinkedIn Job Posting"
referred : "No"
salary : "$100,000 - $120,000"
visa_status : "H1 Visa"
work_authorization : "I am authorized to work in the country in which this job will be performed"