first name: "Maryam"
last name: "Syeda"
your name: "Maryam Syeda"
pronouns : "she/her"
gender : "Female"
email: "maryamsyeda.work@gmail.com"
phone: "(209) 831-2991"
address: "Dublin, CA"
city: "Pleasanton"
state: "California"
zip: "94566"
country: "United States"
job posting: "LinkedIn Job Posting"
degree: "Master"
major degree: "Acibadem University"
work experience: "8-11 more years"
referred: "No"
# salary: "$100,000 - $120,000"
work status : "US Citizen"
work authorization : "I am authorized to work in the country in which this job will be performed"